---
- hosts: all
  become: true
  become_method: sudo 
  tasks:
  - name: Install packages
    apt: 
      name: ['python-pip', 'git', 'apache2'] 
      state: latest
    when: ansible_distribution == 'Ubuntu' 