---
- hosts: all
  any_errors_fatal: True
  become: true
  become_method: sudo 
  tasks:
  - name: Install packages
    apt: 
      name: ['python-pip', 'git', 'apache2' , 'tree'] 
      state: latest
    ignore_errors: yes
    when: ansible_distribution == 'Ubuntu' 