---
- name: add user and generate key, print public key
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
  - name: Remove the user 'ansible'
    user: 
      name: ansible 
      state: absent 
      remove: yes

  - name: Create user
    user: name=user shell=/bin/bash home=/srv/user groups=admin,sudo generate_ssh_key=yes ssh_key_bits=2048

- name: Set password to user
  shell: echo user:plain_text_password | sudo chpasswd
  no_log: True
      state: present 
      register: new_user_key
  - debug: msg="{{ new_user_key.ssh_public_key }}"

  - name: Fetch the keyfile from the node to master
    tags: run
    fetch: 
      src: "~/.ssh/id_rsa.pub"
      dest: "buffer/{{ansible_hostname}}-id_rsa.pub"
      flat: yes

  - name: Copy the key add to authorized_keys using Ansible module
    tags: runcd
    authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file','buffer/{{item}}-id_rsa.pub')}}"
    when: "{{ item != ansible_hostname }}"
    with_items: 
      - "{{ groups['multi'] }}"       